# profiles/prod.yml — 本番向け（セキュア設定を強化）
extends: "base.yml"
env:
  APP_ENV: "production"
  LOG_LEVEL: "info"
  SYNC_MAX_PER_CYCLE: 1000
  SYNC_DB_MIN_ROWS: 100
  HTTP_TIMEOUT: 30
  HTTP_RETRY: 3
  STORAGE_BASE: "storage"

# -- env_matrix 参照キー（placeholder。実値は .env / CI secrets で注入）
# DB_HOST=…
# DB_NAME=…
# DB_PASS=…
# DB_PORT=…
# DB_USER=…
# SMTP_HOST=…
# SMTP_PASS=…
# SMTP_PORT=…
# SMTP_USER=…
# STORAGE_BUCKET=…
# STORAGE_DRIVER=…
# STORAGE_REGION=…
# TENANT_SALT=…
