id: 30_imports_cli
title: CLI群（sync/build_rules/import_db）
model: gpt-5-codex
max_output_tokens: 8192
include:
  - features/cli.md
  - features/imports.md
outputs:
  must_create:
    - cli/sync.php
    - cli/build_rules.php
    - cli/import_db.php
acceptance:
  evidence:
    - evidence/runtime/CLI_OK.txt
  tests_phase: phase_b
