name: "Codex Generate (dispatcher)"

on:
  push:
    branches: ["main"]
    paths:
      - "spec/**"
      - "AGENTS.md"
      - ".github/workflows/codex.yml"
      - "ai/prompt.md"
  workflow_dispatch:
    inputs:
      mode:
        description: "実行モード: full(全集成) / incremental(差分)"
        required: false
        default: "full"
        type: string
      model:
        description: "OpenAIモデル名（空欄可）"
        required: false
        default: ""
        type: string

jobs:
  generate:
    uses: ./.github/workflows/codex-generate.yml
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    with:
      mode:  ${{ inputs.mode  || 'full' }}
      model: ${{ inputs.model || '' }}
