name: "Codex PR cleanup"

on:
  pull_request_target:
    types: ["closed"]

permissions:
  contents: write

jobs:
  delete-ai-batch:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: "ubuntu-latest"
    steps:
      - name: "Delete head branch"
        uses: "actions/github-script@v7"
        with:
          script: |
            const pr = context.payload.pull_request;
            const sameRepo = pr.head.repo.full_name === `${context.repo.owner}/${context.repo.repo}`;
            if (!sameRepo) { core.notice("Head is a fork; skip branch delete."); return; }
            const headRef = pr.head.ref;
            if (!headRef.startsWith("ai/codex/batch-")) { core.notice(`Head ${headRef} not ai/codex/batch-*; skip.`); return; }
            await github.rest.git.deleteRef({ owner: context.repo.owner, repo: context.repo.repo, ref: `heads/${headRef}` });
            core.info(`Deleted heads/${headRef}`);
