name: "Codex"

on:
  workflow_dispatch: {}

permissions:
  contents: "write"

defaults:
  run:
    shell: "bash"

jobs:
  generate:
    name: "Generate from specs (full → new branch)"
    runs-on: "ubuntu-24.04"

    env:
      SPEC_ROOT: "spec"
      SPEC_DIRS: "env foundation features tests"   # ← 誤記 fountation を排除
      PROMPT_FILE: "ai/prompt.md"
      PATCH_FILE: "ai/patch.diff"
      FILES_JSON: "ai/files.json"
      OPENAI_MODEL: "gpt-5-codex"                  # ← モデル固定
      OPENAI_API_KEY: "${{ secrets.OPENAI_API_KEY }}"
      OPENAI_BASE_URL: "${{ secrets.OPENAI_BASE_URL }}"
      BRANCH_PREFIX: "codex/autogen"
      MAX_OUT_TOKENS: "12288"                      # ← 先頭欠落を防ぐため拡張
      TEMPERATURE: "0"
      CURL_TIMEOUT: "120"

    steps:
      - name: "Checkout main"
        uses: "actions/checkout@v4"
        with:
          ref: "main"
          fetch-depth: "1"
          set-safe-directory: "true"

      - name: "Preflight"
        run: |
          set -euo pipefail
          if [ -z "${OPENAI_API_KEY:-}" ]; then
            echo "::error::OPENAI_API_KEY is not set"; exit 1
          fi
          mkdir -p ai
          # jq/gnu tools の存在確認（Runner には入っていますが一応）
          command -v jq >/dev/null || (sudo apt-get update && sudo apt-get install -y jq)

      - name: "Compose prompt (FULL from specs)"
        id: compose
        run: |
          set -euo pipefail
          : > "ai/allowed_paths.txt"
          : > "$PROMPT_FILE"

          # 言語ヒント抽出
          LANG_HINT=""
          for root in "${SPEC_ROOT}/env" "${SPEC_ROOT}/foundation" "${SPEC_ROOT}/features" "${SPEC_ROOT}"; do
            [ -d "$root" ] || continue
            hit="$(grep -R -n -i -E "^\s*(language|runtime\.language|lang|stack\.language|runtime)\s*[:=]\s*" "$root" 2>/dev/null | head -n1 || true)"
            if [ -n "$hit" ]; then
              LANG_HINT="$(printf "%s" "$hit" | sed -E "s/.*[:=]\s*//; s/[\",]//g; s/\s+$//;" | tr "A-Z" "a-z")"
              break
            fi
          done
          if [ -z "$LANG_HINT" ] && [ -f "${SPEC_ROOT}/env/policies.md" ]; then
            line="$(grep -i -m1 -E "\b(php|typescript|javascript|node\.js|python|golang|go|ruby|java|c#|\.net)\b" "${SPEC_ROOT}/env/policies.md" || true)"
            if   printf "%s" "$line" | grep -qi "\bphp\b"; then LANG_HINT="php"
            elif printf "%s" "$line" | grep -qiE "\btypescript|javascript|node\.js\b"; then LANG_HINT="typescript"
            elif printf "%s" "$line" | grep -qi "\bpython\b"; then LANG_HINT="python"
            elif printf "%s" "$line" | grep -qiE "\bgolang|\b go \b"; then LANG_HINT="go"
            elif printf "%s" "$line" | grep -qi "\bruby\b"; then LANG_HINT="ruby"
            elif printf "%s" "$line" | grep -qi "\bjava\b"; then LANG_HINT="java"
            elif printf "%s" "$line" | grep -qiE "\bc#|\.net\b"; then LANG_HINT="csharp"
            fi
          fi
          case "${LANG_HINT:-}" in
            php*|composer*|psr*)              LANG_HINT="php" ;;
            ts|typescript*|node*|javascript*) LANG_HINT="typescript" ;;
            py|python*)                        LANG_HINT="python" ;;
            go|golang*)                        LANG_HINT="go" ;;
            ruby*)                             LANG_HINT="ruby" ;;
            java*)                             LANG_HINT="java" ;;
            c#|dotnet*|.net*|cs)              LANG_HINT="csharp" ;;
            "" )                               LANG_HINT="auto" ;;
          esac
          echo "Language from specs: ${LANG_HINT}"

          # ALLOWED_PATHS の抽出
          grep -R -n -E "(^|\s)(file|path|destination|output|生成先|出力先)\s*:\s*([A-Za-z0-9_./-]+\.[A-Za-z0-9]+)" "$SPEC_ROOT" \
            | sed -E "s/.*:\s*//; s/[\"']//g" \
            | grep -E "[/A-Za-z0-9_.-]+\.[A-Za-z0-9]+" >> "ai/allowed_paths.txt" || true
          grep -R -h -E "[/A-Za-z0-9_.-]+\.(php|ts|tsx|js|jsx|py|rb|go|java|cs|sql|html|css|yml|yaml|json|ini|xml)" "$SPEC_ROOT" \
            | grep -o -E "[/A-Za-z0-9_.-]+\.(php|ts|tsx|js|jsx|py|rb|go|java|cs|sql|html|css|yml|yaml|json|ini|xml)" >> "ai/allowed_paths.txt" || true
          grep -R -h -E "(^|\s)(dir|directory|folder|ディレクトリ)\s*:\s*[A-Za-z0-9_./-]+/?" "$SPEC_ROOT" \
            | sed -E "s/.*:\s*//; s/[\"']//g" | awk '{gsub(/\/?$/,"/");print}' >> "ai/allowed_paths.txt" || true
          sed -E "s#^\./##; s#//+#/#g" -i "ai/allowed_paths.txt" || true
          LC_ALL=C sort -u "ai/allowed_paths.txt" -o "ai/allowed_paths.txt"

          # プロンプト本体
          {
            printf "# Codex generation prompt\n\n"
            printf "## LANGUAGE (MUST)\n\nlanguage: %s\n" "$LANG_HINT"
            printf "\n## ALLOWED_PATHS (only modify/create under these; NEVER touch ai/)\n\n"
            if [ -s "ai/allowed_paths.txt" ]; then
              while IFS= read -r line; do printf -- "- %s\n" "$line"; done < "ai/allowed_paths.txt"
            else
              case "$LANG_HINT" in
                php)         printf -- "- app.php\n- public/\n- src/\n- tests/\n- composer.json\n" ;;
                typescript)  printf -- "- src/\n- app/\n- package.json\n- tsconfig.json\n- vite.config.*\n" ;;
                python)      printf -- "- src/\n- app/\n- requirements.txt\n- pyproject.toml\n" ;;
                *)           printf -- "- /\n" ;; # 最終手段
              esac
              printf "\nDo NOT modify ai/ directory.\n"
            fi
            printf "\n## Example header (force unified diff)\n\ndiff --git a/app.php b/app.php\n"
            printf "\n## STRICT OUTPUT RULES\n\n"
            printf -- "- Output ONE Git unified diff (UTF-8). No prose, no code fences.\n"
            printf -- "- MUST start with: diff --git a/<path> b/<path>\n"
            printf -- "- Follow LANGUAGE; respect ALLOWED_PATHS strictly.\n"
            printf -- "- Include real code (no placeholders). If initial attempt fails, still SYNTHESIZE a complete diff that fulfills the specs.\n"
          } >> "$PROMPT_FILE"

          # 仕様書を連結
          tmp_list="$(mktemp)"
          for d in $SPEC_DIRS; do
            [ -d "${SPEC_ROOT}/${d}" ] || continue
            find "${SPEC_ROOT}/${d}" -type f \( -name "*.md" -o -name "*.txt" -o -name "*.yaml" -o -name "*.yml" -o -name "*.json" \) >> "$tmp_list"
          done
          LC_ALL=C sort -o "$tmp_list" "$tmp_list" || true
          while IFS= read -r f; do
            printf "\n### %s\n\n" "$f" >> "$PROMPT_FILE"
            sed -e "s/\r$//" "$f" | head -n 4000 >> "$PROMPT_FILE"
          done < "$tmp_list"
          rm -f "$tmp_list"

          echo "LANG_HINT=${LANG_HINT}" >> "$GITHUB_OUTPUT"

      - name: "Generate unified diff, commit to new branch, push"
        id: gen
        run: |
          set -euo pipefail

          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          MODEL="${OPENAI_MODEL}"
          BASE="${OPENAI_BASE_URL:-https://api.openai.com}"
          ENDPOINT="${BASE%/}/v1/responses"
          BRANCH_NAME="${BRANCH_PREFIX}-${GITHUB_RUN_ID}"
          git checkout -b "${BRANCH_NAME}"

          # 抽出 jq（多系統に耐える）
          cat > "ai/extract.jq" << 'JQ'
          def texts:
            (try(.output_text) // empty),
            (try(.output[]?.content[]?.text) // empty),
            (try(.choices[0].message.content) // empty),
            (try(.choices[0].text) // empty);
          [ texts ] | map(select(type=="string" and . != "")) | first // ""
          JQ

          # 1st request（diff 専用）
          jq -n --arg model "$MODEL" --arg max "$MAX_OUT_TOKENS" --arg temp "$TEMPERATURE" \
                --arg sys $'Output ONLY a Git unified diff.\nMUST start with: diff --git a/<path> b/<path>\nNo prose or fences.' \
                --rawfile prompt "$PROMPT_FILE" \
            '{ "model":$model, "max_output_tokens":($max|tonumber), "temperature":($temp|tonumber),
               "input":[ {"role":"system","content":[{"type":"input_text","text":$sys}]},
                         {"role":"user","content":[{"type":"input_text","text":$prompt}]} ] }' > "ai/request.json"

          resp_with_code="$(mktemp)"
          curl -sS --max-time "$CURL_TIMEOUT" \
               -H "Authorization: Bearer ${OPENAI_API_KEY}" -H "Content-Type: application/json" \
               -w "\n%{http_code}\n" -d @ai/request.json "$ENDPOINT" | tee "$resp_with_code" >/dev/null
          status="$(tail -n1 "$resp_with_code")"
          head -n -1 "$resp_with_code" > "ai/response.json"
          rm -f "$resp_with_code"
          [ "$status" -lt 300 ] || { echo "::error::OpenAI error ${status}"; exit 3; }

          jq -r -f "ai/extract.jq" "ai/response.json" > "ai/out.txt"
          # フェンス等を除去
          sed -E -e '1{/^```[a-zA-Z-]*[[:space:]]*$/d;}' -e '${/^```[[:space:]]*$/d;}' -i "ai/out.txt" || true
          # パッチ抽出（BOM/空行/Index:/*** も許容）
          awk 'f||/^(diff --git|--- a\/|\*\*\* |Index: )/{f=1; print}' "ai/out.txt" > "$PATCH_FILE" || true

          is_unified=0
          if grep -Eq "^(diff --git|--- (a\/|\/dev\/null)|Index: |\*\*\* )" "$PATCH_FILE" \
             && grep -Eq "(\+\+\+ b\/|^diff --git|^--- b\/)" "$PATCH_FILE"; then
            is_unified=1
          fi

          # repair（2回まで、プロンプト再投入）
          if [ "$is_unified" -ne 1 ]; then
            echo "::warning::first attempt not a unified diff; repairing"
            for i in 1 2; do
              jq -n --arg model "$MODEL" --arg max "$MAX_OUT_TOKENS" --arg temp "$TEMPERATURE" \
                    --arg sys $'Output ONLY a Git unified diff.\nMUST start with: diff --git a/<path> b/<path>\nNo prose or fences.' \
                    --rawfile prev "$PROMPT_FILE" \
                '{ "model":$model, "max_output_tokens":($max|tonumber), "temperature":($temp|tonumber),
                   "input":[ {"role":"system","content":[{"type":"input_text","text":$sys}]},
                             {"role":"user","content":[{"type":"input_text","text":$prev}]} ] }' > "ai/request.repair.json"

              r_with_code="$(mktemp)"
              curl -sS --max-time "$CURL_TIMEOUT" \
                   -H "Authorization: Bearer ${OPENAI_API_KEY}" -H "Content-Type: application/json" \
                   -w "\n%{http_code}\n" -d @ai/request.repair.json "$ENDPOINT" | tee "$r_with_code" >/dev/null
              rstatus="$(tail -n1 "$r_with_code")"
              head -n -1 "$r_with_code" > "ai/response.repair.json"
              rm -f "$r_with_code"
              [ "$rstatus" -lt 300 ] || { echo "::error::repair call error ${rstatus}"; exit 3; }

              jq -r -f "ai/extract.jq" "ai/response.repair.json" > "ai/out.repair.txt"
              sed -E -e '1{/^```[a-zA-Z-]*[[:space:]]*$/d;}' -e '${/^```[[:space:]]*$/d;}' -i "ai/out.repair.txt" || true
              awk 'f||/^(diff --git|--- a\/|\*\*\* |Index: )/{f=1; print}' "ai/out.repair.txt" > "$PATCH_FILE" || true

              if grep -Eq "^(diff --git|--- (a\/|\/dev\/null)|Index: |\*\*\* )" "$PATCH_FILE" \
                 && grep -Eq "(\+\+\+ b\/|^diff --git|^--- b\/)" "$PATCH_FILE"; then
                is_unified=1; break
              fi
            done
          fi

          # diff 経路
          if [ "$is_unified" -eq 1 ]; then
            if git apply --check "$PATCH_FILE"; then
              git apply --index --whitespace=fix "$PATCH_FILE"
            else
              echo "::warning::git apply check failed; attempting 3-way merge"
              git apply --3way --index --whitespace=fix "$PATCH_FILE" || true
            fi
          fi

          # フォールバック: files-JSON で必ず生成
          if ! git diff --cached --name-only | grep -q "."; then
            echo "::warning::No staged changes after diff path; switching to files-JSON fallback"
            jq -n --arg model "$MODEL" --arg max "$MAX_OUT_TOKENS" --arg temp "$TEMPERATURE" \
                  --arg sys $'Output ONLY a compact JSON with exact key `files`: [{ "path": "relative/path", "content": "UTF-8 file content" }, ...]. No prose, no markdown, no trailing text.' \
                  --rawfile prompt "$PROMPT_FILE" \
              '{ "model":$model, "max_output_tokens":($max|tonumber), "temperature":($temp|tonumber),
                 "input":[ {"role":"system","content":[{"type":"input_text","text":$sys}]},
                           {"role":"user","content":[{"type":"input_text","text":$prompt}]} ] }' > "ai/request.files.json"

            f_with_code="$(mktemp)"
            curl -sS --max-time "$CURL_TIMEOUT" \
                 -H "Authorization: Bearer ${OPENAI_API_KEY}" -H "Content-Type: application/json" \
                 -w "\n%{http_code}\n" -d @ai/request.files.json "$ENDPOINT" | tee "$f_with_code" >/dev/null
            fstatus="$(tail -n1 "$f_with_code")"
            head -n -1 "$f_with_code" > "ai/response.files.json"
            rm -f "$f_with_code"
            [ "$fstatus" -lt 300 ] || { echo "::error::files JSON call error ${fstatus}"; exit 3; }

            # JSON 抽出（安全に）
            jq 'try(.files) // empty' "ai/response.files.json" > "$FILES_JSON"
            if [ ! -s "$FILES_JSON" ] || ! jq -e 'type=="array" and length>0 and all(.[]; has("path") and has("content"))' "$FILES_JSON" >/dev/null; then
              echo "::error::Model did not return valid files JSON"; exit 7
            fi

            # ALLOWED_PATHS を尊重しつつ書き出し（空フォールバック時は全許可。ただし ai/ は禁止）
            allow_all=0
            if [ -s "ai/allowed_paths.txt" ]; then
              mapfile -t ALLOWED < "ai/allowed_paths.txt"
            else
              allow_all=1
            fi

            jq -r '.[] | @base64' "$FILES_JSON" | while read -r row; do
              _jq(){ echo "$row" | base64 -d | jq -r "$1"; }
              p="$(_jq '.path' )"; c="$(_jq '.content')"
              if printf "%s" "$p" | grep -q '^ai/'; then
                echo "::warning::skip ai/ path: $p"; continue
              fi
              ok="$allow_all"
              if [ "$allow_all" -ne 1 ]; then
                for pat in "${ALLOWED[@]}"; do
                  if [ "${p#"$pat"}" != "$p" ] || [ "$p" = "$pat" ]; then ok=1; break; fi
                done
              fi
              if [ "$ok" -ne 1 ]; then
                echo "::warning::skip (not allowed): $p"; continue
              fi
              mkdir -p "$(dirname "$p")"
              printf "%s" "$c" > "$p"
              git add "$p"
            done
          fi

          if ! git diff --cached --name-only | grep -q "."; then
            echo "::error::No changes staged after all paths"; exit 6
          fi

          git commit -m "codex(full): generated from specs via ${MODEL}"
          git push origin "HEAD:${BRANCH_NAME}"

          echo "branch=${BRANCH_NAME}" >> "$GITHUB_OUTPUT"
          echo "Generated branch: ${BRANCH_NAME}"

      - name: "Upload AI artifacts"
        uses: "actions/upload-artifact@v4"
        with:
          name: "ai-artifacts"
          if-no-files-found: "ignore"
          path: |
            ai/prompt.md
            ai/allowed_paths.txt
            ai/request.json
            ai/response.json
            ai/out.txt
            ai/request.repair.json
            ai/response.repair.json
            ai/out.repair.txt
            ai/patch.diff
            ai/request.files.json
            ai/response.files.json
            ai/files.json
