name: "Codex Generate (spec-driven)"

on:
  workflow_call:
    inputs:
      mode:
        description: "実行モード: full（全生成）/ incremental（差分）"
        required: false
        default: "full"
        type: string
      model:
        description: "OpenAI モデル名（任意）"
        required: false
        default: ""
        type: string
    secrets:
      OPENAI_API_KEY:
        description: "OpenAI API Key"
        required: true

  workflow_dispatch:
    inputs:
      mode:
        description: "実行モード: full（全生成）/ incremental（差分）"
        required: false
        default: "full"
        type: string
      model:
        description: "OpenAI モデル名（任意）"
        required: false
        default: ""
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  generate:
    runs-on: "ubuntu-latest"

    # ← ジョブ直下の env は 1 か所に統一
    env:
      PROMPT_FILE: "ai/prompt.md"
      DEFECTS_DIR: "ai/defects"
      SPEC_FOUNDATION: "spec/foundation/README.md spec/foundation/file-globs.yml spec/foundation/language.json"
      SPEC_ENVS: "spec/env-profiles/*.yml"
      SPEC_FEATURES: "spec/features/*.md spec/features/*.yml spec/features/*.json"
      SPEC_TESTS: "spec/tests/**/*.md spec/tests/**/*.yml spec/tests/**/*.json"
      ALLOWLIST_FILE: "ai/allowlist.txt"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Preflight: check OPENAI_API_KEY"
        shell: "bash"
        run: |
          set -euo pipefail
          if [ -z "${OPENAI_API_KEY:-}" ]; then
            echo "::error::OPENAI_API_KEY is missing"
            exit 1
          fi
          echo "OPENAI_API_KEY present"

      - name: "Build composite prompt from specs"
        shell: "bash"
        run: |
          set -euo pipefail
          mkdir -p "ai" "ai/defects"
          : > "${PROMPT_FILE}"

          add() { [ -f "$1" ] && { printf "\n\n# %s\n\n" "$1" >> "${PROMPT_FILE}"; cat "$1" >> "${PROMPT_FILE}"; }; }

          for f in ${SPEC_FOUNDATION}; do add "$f"; done
          for f in ${SPEC_ENVS};       do add "$f"; done
          for f in ${SPEC_FEATURES};   do add "$f"; done
          for f in ${SPEC_TESTS};      do add "$f"; done

          {
            echo
            echo "<!-- authoring-rules -->"
            echo "RULES"
            echo "- 生成は idempotent。tests/ 配下に動くテストを必ず同梱。"
            echo "- 既存ファイルがある場合は上書き可。仕様が勝つ。"
            echo "- 曖昧な場合は最小実装を生成し、tests で補う。"
            echo "<!-- /authoring-rules -->"
          } >> "${PROMPT_FILE}"

      - name: "Guard: forbid touching protected paths"
        shell: "bash"
        run: |
          set -euo pipefail
          printf "%s\n" ".git/**" ".github/**" "dist/**" "evidence/**" > "${ALLOWLIST_FILE}"

      - name: "Run Codex"
        id: "codex"
        uses: "openai/codex-action@v2"
        with:
          openai-api-key: "${{ secrets.OPENAI_API_KEY }}"
          prompt-file: "${{ env.PROMPT_FILE }}"
          model: "${{ inputs.model || 'gpt-4.1-mini' }}"
          sandbox: "workspace-write"

      - name: "Show diff summary"
        shell: "bash"
        run: |
          set -euo pipefail
          git status --porcelain=v1 || true
          git diff --stat || true

      - name: "Configure git author"
        shell: "bash"
        run: |
          set -euo pipefail
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name  "github-actions[bot]"

      - name: "Commit and create PR (if changes)"
        shell: "bash"
        run: |
          set -euo pipefail
          if git diff --quiet && git diff --cached --quiet; then
            echo "No changes; skipping PR."
            exit 0
          fi
          BRANCH="ai/codex/batch-${GITHUB_RUN_ID}"
          git checkout -b "${BRANCH}"
          git add -A
          git commit -m "chore(ai): apply Codex changes (mode=${{ inputs.mode || 'full' }})"
          gh pr create \
            --title "AI: Codex changes (mode=${{ inputs.mode || 'full' }})" \
            --body  "Automated changes generated by Codex from specs." \
            --base  "main" \
            --head  "${BRANCH}" || true
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
