name: "Codex Generate (dispatcher)"

on:
  push:
    branches: ["**"]
    paths: ["spec/**", "AGENTS.md"]
  workflow_dispatch:
    inputs:
      mode:
        description: "実行モード: full(再生成) / incremental(差分)"
        required: false
        default: "full"
      model:
        description: "（任意）OpenAIモデル名（未指定＝既定）"
        required: false

jobs:
  call-generate:
    uses: ".github/workflows/codex-generate.yml"
    secrets: inherit
    with:
      mode: "${{ github.event.inputs.mode || 'full' }}"
      model: "${{ github.event.inputs.model || '' }}"
