name: "Codex Generate (spec-driven, supports full wipe)"

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "実行モード: full（全面再生成） / incremental（差分）"
        required: false
        default: "full"
      model:
        description: "OpenAI モデル（未指定ならデフォルト）"
        required: false
        default: ""
  workflow_call:
    inputs:
      mode:
        required: false
        default: "full"
        type: string
      model:
        required: false
        default: ""
        type: string
    secrets:
      OPENAI_API_KEY:
        required: true

permissions:
  contents: "write"
  pull-requests: "write"

env:
  # 仕様書（順番どおり連結してプロンプトにします）
  SPEC_FILES: |
    spec/generation.txt
    spec/testing.txt
    spec/environment.txt
    spec/functional.txt
  PROMPT_FILE: "ai/prompt.md"
  PROMPT_COMBINED: "ai/prompt.combined.md"

jobs:
  generate:
    name: "generate"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - name: "Preflight: check OPENAI_API_KEY"
        shell: "bash"
        run: |
          set -euo pipefail
          if [ -z "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "::error::OPENAI_API_KEY is missing."
            exit 1
          fi
          echo "OK"

      - name: "Full mode: wipe workspace (keep protected dirs)"
        if: ${{ inputs.mode == 'full' }}
        shell: "bash"
        run: |
          set -euo pipefail

          # 1) 保護パターン（優先: ai/allowlist.txt、無ければ既定）
          if [ -f "ai/allowlist.txt" ]; then
            echo "::notice::Using ai/allowlist.txt"
            KEEP_PAT="$(grep -vE '^\s*($|#)' ai/allowlist.txt | paste -sd '|' -)"
            [ -z "${KEEP_PAT}" ] && KEEP_PAT='^(spec/|ai/|\.github/)'
          else
            KEEP_PAT='^(spec/|ai/|\.github/)'
          fi
          echo "KEEP_PAT=${KEEP_PAT}"

          # 2) Git 管理ファイルのうち、保護対象以外を削除
          git ls-files | grep -vE "${KEEP_PAT}" | xargs -r git rm -f

          # 3) 非 Git ファイルも掃除（保護対象と .git は除外）
          find . -type f \
            ! -path "./.git/*" \
            | grep -vE "/\.git/|${KEEP_PAT}" | xargs -r rm -f

          # 4) 空ディレクトリを整理
          find . -type d -empty \
            ! -path "." \
            ! -path "./.git" \
            ! -path "./.git/*" \
            | grep -vE "/\.git$|${KEEP_PAT}" \
            | xargs -r rmdir || true

          echo "::notice::Workspace wiped (protected kept)."

      - name: "Build prompt from specs"
        id: "build_prompt"
        shell: "bash"
        run: |
          set -euo pipefail
          mkdir -p ai
          : > "${{ env.PROMPT_COMBINED }}"
          echo "# Codex generation prompt" >> "${{ env.PROMPT_COMBINED }}"
          echo "" >> "${{ env.PROMPT_COMBINED }}"
          echo "- MODE: ${{ inputs.mode }}" >> "${{ env.PROMPT_COMBINED }}"
          echo "" >> "${{ env.PROMPT_COMBINED }}"
          while IFS= read -r f; do
            [ -z "$f" ] && continue
            if [ -f "$f" ]; then
              echo "" >> "${{ env.PROMPT_COMBINED }}"
              echo "<!-- file: $f -->" >> "${{ env.PROMPT_COMBINED }}"
              echo "" >> "${{ env.PROMPT_COMBINED }}"
              cat "$f" >> "${{ env.PROMPT_COMBINED }}"
              echo "" >> "${{ env.PROMPT_COMBINED }}"
            else
              echo "::warning::Spec file not found: $f"
            fi
          done <<'EOF_SPECS'
          ${{ env.SPEC_FILES }}
          EOF_SPECS
          cp -f "${{ env.PROMPT_COMBINED }}" "${{ env.PROMPT_FILE }}"

      - name: "Run Codex"
        uses: "openai/codex-action@main"
        with:
          openai-api-key: "${{ secrets.OPENAI_API_KEY }}"
          prompt-file: "${{ env.PROMPT_COMBINED }}"
          model: "${{ inputs.model || '' }}"
          sandbox: "workspace-write"

      - name: "Show diff summary"
        id: "diff"
        shell: "bash"
        run: |
          set -euo pipefail
          echo "=== git status ==="
          git status --porcelain=v1
          echo "=== diff stat ==="
          git diff --stat || true
          if git status --porcelain=v1 | grep -q .; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: "Configure git author"
        if: ${{ steps.diff.outputs.changed == 'true' }}
        shell: "bash"
        run: |
          set -euo pipefail
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name  "github-actions[bot]"

      - name: "Create Pull Request"
        if: ${{ steps.diff.outputs.changed == 'true' }}
        uses: "peter-evans/create-pull-request@v7"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          add-paths: |
            .
          commit-message: "chore(ai): apply Codex generation"
          title: "AI: Codex updates (mode=${{ inputs.mode }})"
          body: |
            Automated changes generated by Codex.
            - mode: `${{ inputs.mode }}`
            - model: `${{ inputs.model || 'default' }}`
            - specs: `${{ env.SPEC_FILES }}`
          branch: "ai/codex/batch-${{ github.run_id }}"
          base: "main"
          signoff: false
          delete-branch: true

      - name: "No changes"
        if: ${{ steps.diff.outputs.changed != 'true' }}
        shell: "bash"
        run: |
          echo "No changes to commit."
