name: "Codex Generate (dispatcher)"

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "実行モード: full（全生成）/ incremental（差分）"
        required: false
        default: "full"
        type: string
      model:
        description: "OpenAI モデル名（任意）"
        required: false
        default: ""
        type: string
  push:
    branches: ["main"]
    paths:
      - "spec/**"
      - ".github/workflows/codex.yml"

permissions:
  contents: write
  pull-requests: write

jobs:
  generate:
    uses: ".github/workflows/codex-generate.yml"
    with:
      mode: "${{ inputs.mode || 'full' }}"
      model: "${{ inputs.model || '' }}"
    secrets:
      OPENAI_API_KEY: "${{ secrets.OPENAI_API_KEY }}"
