name: "Codex Generate (dispatcher)"

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "実行モード: full（全生成） / incremental（差分）"
        type: string
        required: false
        default: "full"
      model:
        description: "OpenAI モデル名（任意）"
        type: string
        required: false
        default: ""
  push:
    branches:
      - "main"
    paths:
      - "spec/**"
      - ".github/workflows/codex.yml"

permissions:
  contents: write
  pull-requests: write

jobs:
  generate:
    uses: ./.github/workflows/codex-generate.yml
    with:
      mode: "${{ inputs.mode || 'full' }}"
      model: "${{ inputs.model || '' }}"
    secrets: inherit
