# .github/workflows/codex.yml
name: "Codex Generate (dispatcher)"

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "実行モード: full(全生成) / incremental(差分)"
        required: false
        default: "full"
        type: choice
        options: ["full", "incremental"]
      model:
        description: "OpenAI モデル名 (任意)"
        required: false
        default: ""
        type: string

  push:
    branches: ["main"]
    # 仕様書更新時のみ起動させたい場合は paths で限定
    paths:
      - "spec/**"

permissions:
  contents: write
  pull-requests: write

jobs:
  generate:
    # push時、コミットメッセージに [skip-codex] があればスキップ
    if: ${{ github.event_name != 'push' || !contains(github.event.head_commit.message, '[skip-codex]') }}
    # ローカル再利用ワークフロー呼び出しは必ず "./" を付ける
    uses: ./.github/workflows/codex-generate.yml
    with:
      mode: "${{ inputs.mode || 'full' }}"
      model: "${{ inputs.model || '' }}"
    # 秘密情報はそのまま継承
    secrets: inherit
